Последовательность проведения анализа зависит от задачи. 

EDA — это своего рода искусство!

Однако всё же можно выделить основные шаги:

Посмотреть на данные.

Проверить данные на пустые значения.

Проверить данные на дублированные/полностью скоррелированные значения.

Проверить данные на наличие выбросов.

Отобрать данные, пригодные для дальнейшего построения модели.

Снова и снова возвращаться к предыдущим пунктам, пока модель не заработает как надо.

Организационная информация
Что нужно сделать?


Ознакомиться с дополнительными модулями этого юнита: *STAT&BASIC-2–STAT&BASIC-5.

Вместе с автором модуля провести разведывательный анализ и найти ответ на вопрос:
 «Какие параметры влияют на оценку шоколадных батончиков?».

Внимательно ознакомиться с описанием задачи для самостоятельной работы.

Прочитать рекомендации по выполнению самостоятельного проекта.

Активно принимать участие в канале Slack #0-real_ds_анализ_данных.

Выполнить проект и загрузить его на git.

Сдать свой ноутбук с решением на проверку ментору.

Получить обратную связь от ментора.

В этом кейсе мы познакомимся с тем, как проводить EDA на примере исследования о качестве шоколадных батончиков. EDA поможет нам первично проверить гипотезу о связи различных переменных с рейтингом батончика.

В датасете представлены следующие данные:


Bar id — ID батончика в базе данных

Company (Maker-if known) — название компании, изготовившей батончик.

Specific Bean Origin or Bar Name — точное место происхождения какао-бобов.

Broad Bean Origin — название региона, где были выращены какао-бобы.

Company Location — страна, в которой произведён шоколадный батончик.

Bean Type — вид какао-бобов, используемых в батончике.

REF — числовое значение, показывающее, как давно ревью было добавлено в базу. Чем выше значение, тем более свежее ревью.

Review Date — год публикации рецензии.

Cocoa Percent — процент какао в шоколаде.

Rating — оценка батончика фокус-группой.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from itertools import combinations
from scipy.stats import ttest_ind

pd.set_option('display.max_rows', 50) # показывать больше строк
pd.set_option('display.max_columns', 50) # показывать больше колонок

cacao = pd.read_csv('cacao_flavors.csv')

In [2]:
cacao.info

<bound method DataFrame.info of       Bar id Company \n(Maker-if known) Specific Bean Origin\nor Bar Name  \
0          1                   A. Morin                       Agua Grande
1          2                   A. Morin                             Kpime
2          3                   A. Morin                            Atsane
3          4                   A. Morin                             Akata
4          5                   A. Morin                            Quilla
...      ...                        ...                               ...
1790    1791                     Zotter                              Peru
1791    1792                     Zotter                             Congo
1792    1793                     Zotter                      Kerala State
1793    1794                     Zotter                      Kerala State
1794    1795                     Zotter                Brazil, Mitzi Blue

       REF  Review\nDate Cocoa\nPercent Company\nLocation  Rating Bean\nType  \
0     1876          2016            63%            France   11.50
1     1676          2015            70%            France    2.75
2     1676          2015           670%            France    3.00
3     1680          2015            70%            France    3.50
4     1704          2015            70%            France    3.50
...    ...           ...            ...               ...     ...        ...
1790   647          2011            70%           Austria    3.75
1791   749          2011            65%           Austria    3.00  Forastero
1792   749          2011            65%           Austria    3.50  Forastero
1793   781          2011            62%           Austria    3.25
1794   486          2010            65%           Austria    3.00

     Broad Bean\nOrigin
0              Sao Tome
1                  Togo
2                  Togo
3                  Togo
4                  Peru
...                 ...
1790               Peru
1791              Congo
1792              India
1793              India
1794             Brazil

[1795 rows x 10 columns]>

In [7]:
display(cacao.head(10))
cacao.info()

,Bar id,Company \n(Maker-if known),Specific Bean Origin\nor Bar Name,REF,Review\nDate,Cocoa\nPercent,Company\nLocation,Rating,Bean\nType,Broad Bean\nOrigin
0,1,A. Morin,Agua Grande,1876,2016,63%,France,11.50,,Sao Tome
1,2,A. Morin,Kpime,1676,2015,70%,France,2.75,,Togo
2,3,A. Morin,Atsane,1676,2015,670%,France,3.00,,Togo
3,4,A. Morin,Akata,1680,2015,70%,France,3.50,,Togo
4,5,A. Morin,Quilla,1704,2015,70%,France,3.50,,Peru
5,6,A. Morin,Carenero,1315,2014,70%,France,2.75,Criollo,Venezuela
6,7,A. Morin,Cuba,1315,2014,70%,France,3.50,,Cuba
7,8,A. Morin,Sur del Lago,1315,2014,70%,France,11.50,Criollo,Venezuela
8,9,,Puerto Cabello,1319,2014,70%,France,3.75,Criollo,Venezuela
9,10,A. Morin,Pablino,1319,2014,70%,France,4.00,,Peru

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Bar id                            1795 non-null   int64
 1   Company
(Maker-if known)         1795 non-null   object
 2   Specific Bean Origin
or Bar Name  1795 non-null   object
 3   REF                               1795 non-null   int64
 4   Review
Date                       1795 non-null   int64
 5   Cocoa
Percent                     1795 non-null   object
 6   Company
Location                  1795 non-null   object
 7   Rating                            1795 non-null   float64
 8   Bean
Type                         1794 non-null   object
 9   Broad Bean
Origin                 1794 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 140.4+ KB

In [3]:
#Для удобства использования pandas переименуем все столбцы:

cacao.columns

Index(['Bar id', 'Company \n(Maker-if known)',
       'Specific Bean Origin\nor Bar Name', 'REF', 'Review\nDate',
       'Cocoa\nPercent', 'Company\nLocation', 'Rating', 'Bean\nType',
       'Broad Bean\nOrigin'],
      dtype='object')

In [4]:
#еперь рассмотрим все 10 (!) столбцов по отдельности. Но мы с вами не боимся рутинной работы, не так ли?

##Bar id
print(cacao.bar_id.nunique())
plt.plot(cacao.bar_id)

AttributeError: 'DataFrame' object has no attribute 'bar_id'